service: intelligent-engineering-platform

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  memorySize: 512
  timeout: 30
  httpApi:
    cors:
      allowedOrigins:
        - '*'
      allowedHeaders:
        - Content-Type
        - Authorization
        - X-Amz-Date
        - X-Api-Key
        - X-Amz-Security-Token
        - X-Amz-User-Agent
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowCredentials: false
  
  environment:
    STAGE: ${self:provider.stage}
    DYNAMODB_TABLE_PREFIX: ${self:service}-${self:provider.stage}
    JWT_SECRET: ${env:JWT_SECRET}
    BEDROCK_MODEL_ID: ${env:BEDROCK_MODEL_ID, 'anthropic.claude-3-5-sonnet-20241022-v2:0'}
    GEMINI_API_KEY: ${env:GEMINI_API_KEY}
    SES_FROM_EMAIL: ${env:SES_FROM_EMAIL}
    FROM_EMAIL: ${env:FROM_EMAIL}
    FRONTEND_URL: ${env:FRONTEND_URL}
    AWS_BEARER_TOKEN_BEDROCK: ${env:AWS_BEARER_TOKEN_BEDROCK}
    DEFAULT_PROJECT_LIMIT: ${env:DEFAULT_PROJECT_LIMIT, '3'}
    BACKDOOR_USER_EMAIL: ${env:BACKDOOR_USER_EMAIL}
  
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchGetItem
            - dynamodb:BatchWriteItem
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE_PREFIX}-*
        - Effect: Allow
          Action:
            - bedrock:InvokeModel
            - bedrock:InvokeModelWithResponseStream
          Resource:
            - arn:aws:bedrock:${self:provider.region}::foundation-model/${self:provider.environment.BEDROCK_MODEL_ID}
        - Effect: Allow
          Action:
            - ses:SendEmail
            - ses:SendRawEmail
          Resource: '*'
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: '*'
        - Effect: Allow
          Action:
            - xray:PutTraceSegments
            - xray:PutTelemetryRecords
          Resource: '*'

  tracing:
    lambda: true
    apiGateway: true

functions:
  # Authentication Functions
  auth-login:
    handler: dist/handlers/auth.login
    events:
      - http:
          path: /auth/login
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

  auth-register:
    handler: dist/handlers/auth.register
    events:
      - http:
          path: /auth/register
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

  auth-me:
    handler: dist/handlers/auth.me
    events:
      - http:
          path: /auth/me
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
            methods:
              - GET
              - OPTIONS
          authorizer:
            name: authorizer
            type: request

  # Project Functions
  projects-create:
    handler: dist/handlers/projects.create
    events:
      - http:
          path: /projects
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          authorizer:
            name: authorizer
            type: request

  projects-list:
    handler: dist/handlers/projects.list
    events:
      - http:
          path: /projects
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          authorizer:
            name: authorizer
            type: request

  projects-get:
    handler: dist/handlers/projects.get
    events:
      - http:
          path: /projects/{projectId}
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          authorizer:
            name: authorizer
            type: request

  projects-update:
    handler: dist/handlers/projects.update
    events:
      - http:
          path: /projects/{projectId}
          method: put
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          authorizer:
            name: authorizer
            type: request

  projects-delete:
    handler: dist/handlers/projects.delete
    events:
      - http:
          path: /projects/{projectId}
          method: delete
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          authorizer:
            name: authorizer
            type: request

  # AI Generation Functions
  ai-generate-phase:
    handler: dist/handlers/ai.generatePhase
    timeout: 60
    memorySize: 1024
    events:
      - http:
          path: /projects/{projectId}/phases/{phaseId}/generate
          method: post
          cors: true
          authorizer:
            name: authorizer
            type: request

  ai-generate-sprint:
    handler: dist/handlers/ai.generateSprint
    timeout: 60
    memorySize: 1024
    events:
      - http:
          path: /projects/{projectId}/phases/{phaseId}/sprints/{sprintId}/generate
          method: post
          cors: true
          authorizer:
            name: authorizer
            type: request

  # Template Functions
  templates-list:
    handler: dist/handlers/templates.list
    events:
      - http:
          path: /templates
          method: get
          cors: true
          authorizer:
            name: authorizer
            type: request

  templates-generate:
    handler: dist/handlers/templates.generate
    timeout: 60
    events:
      - http:
          path: /templates/generate
          method: post
          cors: true
          authorizer:
            name: authorizer
            type: request

  # Analytics Functions
  analytics-project:
    handler: dist/handlers/analytics.getProjectAnalytics
    events:
      - http:
          path: /projects/{projectId}/analytics
          method: get
          cors: true
          authorizer:
            name: authorizer
            type: request

  # Risk Assessment Functions
  risk-assess:
    handler: dist/handlers/risk.assess
    timeout: 60
    events:
      - http:
          path: /projects/{projectId}/risks/assess
          method: post
          cors: true
          authorizer:
            name: authorizer
            type: request

  # Export Functions
  export-project:
    handler: dist/handlers/export.exportProject
    timeout: 120
    memorySize: 2048
    events:
      - http:
          path: /projects/{projectId}/export
          method: post
          cors: true
          authorizer:
            name: authorizer
            type: request

  # Task Functions
  tasks-list-by-project:
    handler: dist/handlers/tasks.listByProject
    events:
      - http:
          path: /tasks/project/{projectId}
          method: get
          cors: true
          authorizer:
            name: authorizer
            type: request

  tasks-assign:
    handler: dist/handlers/tasks.assignTask
    events:
      - http:
          path: /tasks/assign
          method: post
          cors: true
          authorizer:
            name: authorizer
            type: request

  tasks-update:
    handler: dist/handlers/tasks.updateTask
    events:
      - http:
          path: /tasks/{taskId}
          method: put
          cors: true
          authorizer:
            name: authorizer
            type: request

  # Team Functions
  team-get-members:
    handler: dist/handlers/team.getMembers
    events:
      - http:
          path: /team/{projectId}/members
          method: get
          cors: true
          authorizer:
            name: authorizer
            type: request

  team-get-active:
    handler: dist/handlers/team.getActiveUsers
    events:
      - http:
          path: /team/{projectId}/active
          method: get
          cors: true
          authorizer:
            name: authorizer
            type: request

  team-invite:
    handler: dist/handlers/team.inviteMember
    events:
      - http:
          path: /team/{projectId}/invite
          method: post
          cors: true
          authorizer:
            name: authorizer
            type: request

  # Authorizer Function
  authorizer:
    handler: dist/handlers/authorizer.handler

resources:
  Resources:
    # API Gateway CORS Configuration
    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: ApiGatewayRestApi
    
    GatewayResponseDefault5XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: ApiGatewayRestApi
    
    # DynamoDB Tables
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE_PREFIX}-users
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: EmailIndex
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true

    ProjectsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE_PREFIX}-projects
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: UserIdIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true

    TemplatesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE_PREFIX}-templates
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true

    AIResponseCacheTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE_PREFIX}-ai-cache
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: cacheKey
            AttributeType: S
        KeySchema:
          - AttributeName: cacheKey
            KeyType: HASH
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

plugins: []

package:
  individually: false
  patterns:
    - '!src/**'
    - 'dist/**'
    - 'node_modules/**'
    - '!node_modules/@types/**'
    - '!node_modules/typescript/**'
    - '!node_modules/serverless*/**'
    - '!node_modules/.bin/**'
    - '!node_modules/**/*.md'
    - '!node_modules/**/test/**'
    - '!node_modules/**/tests/**'
    - '!**/*.md'
    - '!**/*.map'
    - '!.env'
    - '!tsconfig.json'
    - '!*.ps1'
    - '!README.md'
    - '!response*.json'
    - '!test-payload.json'
